server.tomcat.accesslog.enabled=true

spring.datasource.url=jdbc:postgresql://dpg-d80hjv3tqb8s73871v0g-a:5432/vetappdb_0hb7?sslmode=require
spring.datasource.username=vetappdb_0hb7_user
spring.datasource.password=uAlcB7of2oJJKhavTAK1iDMUl1pEMVIc
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true