server.port=${PORT:8080}
server.tomcat.accesslog.enabled=true

# =========================
# DATABASE (RENDER POSTGRES)
# =========================
spring.datasource.url=jdbc:postgresql://dpg-d80hjv3tqb8s73871v0g-a.oregon-postgres.render.com:5432/vetappdb_0hb7?sslmode=require
spring.datasource.username=vetappdb_0hb7_user
spring.datasource.password=uAlcB7of2oJJKhavTAK1iDMUl1pEMVIc
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# HIBERNATE / JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =========================
# IMPORTANT (RENDER FIX)
# =========================
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.leak-detection-threshold=20000