server.tomcat.accesslog.enabled=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true

spring.datasource.url=postgresql://vetappdb_0hb7_user:uAlcB7of2oJJKhavTAK1iDMUl1pEMVIc@dpg-d80hjv3tqb8s73871v0g-a/vetappdb_0hb7
spring.datasource.username=vetappdb_0hb7_user
spring.datasource.password=uAlcB7of2oJJKhavTAK1iDMUl1pEMVIc
spring.datasource.driver-class-name=org.postgresql.Driver





